import localFont from "next/font/local";
import { Quicksand } from "next/font/google"; // Import Quicksand
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/context/ThemeContext";
import { Toaster } from "@/components/ui/sonner";

// Define Quicksand font from Google Fonts
const quicksand = Quicksand({
  subsets: ["latin"], // Required: specify the character subset
  weight: ["300", "400", "500", "600", "700"], // Specify weights you want
  variable: "--font-quicksand", // Optional: CSS variable for flexibility
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <ClerkProvider>
        <html lang="en">
          <body
            className={`${quicksand.variable} antialiased`}
          >
            {children}
            <Toaster />
          </body>
        </html>
      </ClerkProvider>
    </ThemeProvider>
  );
}